"""Generate ReqIF XML from Document model."""
from __future__ import annotations
import uuid
import datetime
from xml.etree import ElementTree as ET
from xml.dom import minidom
from md2reqif.model import Document, Requirement

XHTML_NS = "http://www.w3.org/1999/xhtml"


def _uid() -> str:
    return f"_ID_{uuid.uuid4().hex[:12].upper()}"


def _now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")


def write(doc: Document, pretty: bool = True) -> str:
    root = ET.Element("REQ-IF")
    root.set("xmlns", "http://www.omg.org/spec/ReqIF/20110401/reqif.xsd")

    # HEADER
    header = ET.SubElement(root, "THE-HEADER")
    rh = ET.SubElement(header, "REQ-IF-HEADER")
    rh.set("IDENTIFIER", _uid())
    ET.SubElement(rh, "COMMENT").text = "Generated by md2reqif"
    ET.SubElement(rh, "CREATION-TIME").text = _now()
    ET.SubElement(rh, "REQ-IF-TOOL-ID").text = "md2reqif"
    ET.SubElement(rh, "REQ-IF-VERSION").text = "1.0"
    ET.SubElement(rh, "SOURCE-TOOL-ID").text = "md2reqif"
    ET.SubElement(rh, "TITLE").text = doc.title

    all_reqs: list[Requirement] = [r for s in doc.sections for r in s.requirements]
    attr_names: list[str] = sorted({a.name.lower() for r in all_reqs for a in r.attributes})

    core = ET.SubElement(root, "CORE-CONTENT")
    content = ET.SubElement(core, "REQ-IF-CONTENT")

    # DATATYPES
    dts = ET.SubElement(content, "DATATYPES")
    str_dt_id = _uid()
    str_dt = ET.SubElement(dts, "DATATYPE-DEFINITION-STRING")
    str_dt.set("IDENTIFIER", str_dt_id)
    str_dt.set("LAST-CHANGE", _now())
    str_dt.set("LONG-NAME", "String")
    str_dt.set("MAX-LENGTH", "1000")

    xhtml_dt_id = _uid()
    xhtml_dt = ET.SubElement(dts, "DATATYPE-DEFINITION-XHTML")
    xhtml_dt.set("IDENTIFIER", xhtml_dt_id)
    xhtml_dt.set("LAST-CHANGE", _now())
    xhtml_dt.set("LONG-NAME", "XHTML")

    # SPEC-TYPES
    sts = ET.SubElement(content, "SPEC-TYPES")
    req_type_id = _uid()
    req_type = ET.SubElement(sts, "SPEC-OBJECT-TYPE")
    req_type.set("IDENTIFIER", req_type_id)
    req_type.set("LAST-CHANGE", _now())
    req_type.set("LONG-NAME", "Requirement")
    spec_attrs_el = ET.SubElement(req_type, "SPEC-ATTRIBUTES")

    desc_attr_id = _uid()
    da = ET.SubElement(spec_attrs_el, "ATTRIBUTE-DEFINITION-XHTML")
    da.set("IDENTIFIER", desc_attr_id)
    da.set("LAST-CHANGE", _now())
    da.set("LONG-NAME", "ReqIF.Text")
    ET.SubElement(ET.SubElement(da, "TYPE"), "DATATYPE-DEFINITION-XHTML-REF").text = xhtml_dt_id

    attr_def_ids: dict[str, str] = {}
    for an in attr_names:
        aid = _uid()
        attr_def_ids[an] = aid
        ad = ET.SubElement(spec_attrs_el, "ATTRIBUTE-DEFINITION-STRING")
        ad.set("IDENTIFIER", aid)
        ad.set("LAST-CHANGE", _now())
        ad.set("LONG-NAME", an.title())
        ET.SubElement(ET.SubElement(ad, "TYPE"), "DATATYPE-DEFINITION-STRING-REF").text = str_dt_id

    spec_type_id = _uid()
    st = ET.SubElement(sts, "SPECIFICATION-TYPE")
    st.set("IDENTIFIER", spec_type_id)
    st.set("LAST-CHANGE", _now())
    st.set("LONG-NAME", "Requirements Specification")

    # SPEC-OBJECTS
    objs_el = content  # place SPEC-OBJECT elements directly in REQ-IF-CONTENT
    req_to_obj_id: dict[str, str] = {}

    for req in all_reqs:
        obj_id = _uid()
        req_to_obj_id[req.id] = obj_id
        obj = ET.SubElement(objs_el, "SPEC-OBJECT")
        obj.set("IDENTIFIER", obj_id)
        obj.set("LAST-CHANGE", _now())
        obj.set("LONG-NAME", req.id)
        ET.SubElement(ET.SubElement(obj, "TYPE"), "SPEC-OBJECT-TYPE-REF").text = req_type_id
        vals = ET.SubElement(obj, "VALUES")

        dv = ET.SubElement(vals, "ATTRIBUTE-VALUE-XHTML")
        ET.SubElement(ET.SubElement(dv, "DEFINITION"), "ATTRIBUTE-DEFINITION-XHTML-REF").text = desc_attr_id
        tv = ET.SubElement(dv, "THE-VALUE")
        div = ET.SubElement(tv, f"{{{XHTML_NS}}}div")
        p1 = ET.SubElement(div, f"{{{XHTML_NS}}}p")
        p1.text = req.title
        if req.description:
            p2 = ET.SubElement(div, f"{{{XHTML_NS}}}p")
            p2.text = req.description

        for attr in req.attributes:
            key = attr.name.lower()
            if key in attr_def_ids:
                sv = ET.SubElement(vals, "ATTRIBUTE-VALUE-STRING")
                sv.set("THE-VALUE", attr.value)
                ET.SubElement(ET.SubElement(sv, "DEFINITION"), "ATTRIBUTE-DEFINITION-STRING-REF").text = attr_def_ids[key]

    ET.SubElement(content, "SPEC-RELATIONS")

    # SPECIFICATIONS
    specs_el = ET.SubElement(content, "SPECIFICATIONS")
    spec = ET.SubElement(specs_el, "SPECIFICATION")
    spec.set("IDENTIFIER", _uid())
    spec.set("LAST-CHANGE", _now())
    spec.set("LONG-NAME", doc.title)
    ET.SubElement(ET.SubElement(spec, "TYPE"), "SPECIFICATION-TYPE-REF").text = spec_type_id
    children_el = ET.SubElement(spec, "CHILDREN")

    for sec in doc.sections:
        sec_node = ET.SubElement(children_el, "SPEC-HIERARCHY")
        sec_node.set("IDENTIFIER", _uid())
        sec_node.set("LAST-CHANGE", _now())
        ET.SubElement(sec_node, "OBJECT")
        sec_children = ET.SubElement(sec_node, "CHILDREN")
        for req in sec.requirements:
            rn = ET.SubElement(sec_children, "SPEC-HIERARCHY")
            rn.set("IDENTIFIER", _uid())
            rn.set("LAST-CHANGE", _now())
            ET.SubElement(ET.SubElement(rn, "OBJECT"), "SPEC-OBJECT-REF").text = req_to_obj_id[req.id]

    raw = ET.tostring(root, encoding="unicode")
    full = f'<?xml version="1.0" encoding="UTF-8"?>\n{raw}'
    if pretty:
        try:
            parsed = minidom.parseString(full.encode("utf-8"))
            return parsed.toprettyxml(indent="  ", encoding=None)
        except Exception:
            pass
    return full
